name: Build

on:
  push:
    branches: [ "master" ]

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore ./Horizon.sln

    - name: Build
      run: dotnet build ./Horizon.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test ./Horizon.sln --configuration Release --no-restore
      
